export interface ServiceData {
  slug: string;
  name: string;
  category: string;
  tagline: string;
  shortDescription: string;
  fullDescription: string;
  capabilities: string[];
  process: { step: string; title: string; description: string }[];
  relatedIndustries: string[];
  badge?: string;
}

export const servicesData: ServiceData[] = [
  {
    slug: 'public-relations',
    name: 'Public Relations',
    category: 'Core Practice',
    tagline: 'Precision media architecture and earned authority.',
    shortDescription: 'Strategic communications support through Public Relations.',
    fullDescription: 'We help businesses, brands, organizations and industry leaders build visibility, strengthen reputation and create meaningful engagement through strategic communication and proactive media engagement.',
    capabilities: [
      'Strategic Narrative Development',
      'Editorial Pitching & Newsroom Relations',
      'Press Release & Media Advisory Orchestration',
      'Spokesperson Positioning',
      'Executive Op-Ed Placement',
      'Media Perception Analysis',
    ],
    process: [
      { step: '01', title: 'Narrative Discovery', description: 'Comprehensive analysis of brand positioning, media footprint, and stakeholder expectations.' },
      { step: '02', title: 'Strategic Blueprint', description: 'Formulating core message pillars, editorial angles, and outreach schedules.' },
      { step: '03', title: 'Media Engagement', description: 'Direct engagement with premier business editors, broadcast producers, and industry correspondents.' },
      { step: '04', title: 'Impact Synthesis', description: 'Reviewing narrative sentiment, reach, and qualitative message resonance.' },
    ],
    relatedIndustries: ['Real Estate', 'Infrastructure', 'Corporate Organizations'],
  },
  {
    slug: 'media-relations',
    name: 'Media Relations',
    category: 'Media Practice',
    tagline: 'High-trust alliances between leadership and premier journalistic networks.',
    shortDescription: 'Strategic communications support through Media Relations.',
    fullDescription: 'Our seasoned media strategists cultivate enduring, high-trust alliances with the press, ensuring corporate developments, strategic transitions, and milestones receive nuanced and prominent coverage.',
    capabilities: [
      'Editorial Briefings & Press Engagement',
      'Targeted Media Feature Coordination',
      'Broadcast & Audio Interview Placements',
      'Embargo & Distribution Protocols',
      'Media Roundtable & Press Meet Curation',
    ],
    process: [
      { step: '01', title: 'Story Framing', description: 'Translating corporate milestones into compelling business and sector narratives.' },
      { step: '02', title: 'Targeted Outreach', description: 'Engaging beat-specific journalists who shape sector conversation.' },
      { step: '03', title: 'Message Preparation', description: 'Pre-interview briefing packs, anticipated inquiries, and message alignment.' },
      { step: '04', title: 'Ongoing Relations', description: 'Maintaining continual editorial dialogue beyond single announcements.' },
    ],
    relatedIndustries: ['Corporate Organizations', 'Startups', 'Healthcare'],
  },
  {
    slug: 'corporate-communications',
    name: 'Corporate Communications',
    category: 'Advisory Practice',
    tagline: 'Unified narrative governance for complex organizations.',
    shortDescription: 'Strategic communications support through Corporate Communications.',
    fullDescription: 'We align internal leadership, investors, regulatory stakeholders, and the public with clarity, building integrated communications systems that reinforce institutional credibility.',
    capabilities: [
      'Stakeholder Narrative Mapping',
      'Milestone & Announcement Communications',
      'Annual & Organizational Reporting Support',
      'Internal Leadership Alignment',
      'Executive Communications Advisory',
    ],
    process: [
      { step: '01', title: 'Stakeholder Mapping', description: 'Identifying key constituent groups and information channels.' },
      { step: '02', title: 'Message Architecture', description: 'Establishing consistent corporate narrative guides across communication touchpoints.' },
      { step: '03', title: 'Channel Integration', description: 'Deploying synchronized updates across shareholder, media, and internal channels.' },
      { step: '04', title: 'Sentiment Review', description: 'Assessing stakeholder trust and institutional sentiment over time.' },
    ],
    relatedIndustries: ['Corporate Organizations', 'Infrastructure', 'Professional Services'],
  },
  {
    slug: 'reputation-management',
    name: 'Reputation Management',
    category: 'Reputation Practice',
    tagline: 'Protecting and enhancing corporate and institutional goodwill.',
    shortDescription: 'Strategic communications support through Reputation Management.',
    fullDescription: 'Strategic stewardship of corporate goodwill, mitigating reputational risk and building lasting public trust across commercial and institutional landscapes.',
    capabilities: [
      'Corporate Reputation Audits',
      'Digital Footprint & Perception Reviews',
      'Sentiment & Narrative Alignment',
      'Stakeholder Trust Rebuilding Strategies',
      'Advocacy & Third-Party Credibility Support',
    ],
    process: [
      { step: '01', title: 'Reputation Audit', description: 'Reviewing public perception, media coverage, and stakeholder views.' },
      { step: '02', title: 'Fortification Protocol', description: 'Publishing authoritative corporate benchmarks and verified milestones.' },
      { step: '03', title: 'Monitoring & Review', description: 'Active monitoring systems that alert leadership to emerging narrative shifts.' },
      { step: '04', title: 'Long-Term Alignment', description: 'Embedding governance and brand credibility into ongoing media cycles.' },
    ],
    relatedIndustries: ['Healthcare', 'Corporate Organizations', 'Hospitality'],
  },
  {
    slug: 'thought-leadership',
    name: 'Thought Leadership',
    category: 'Executive Advisory',
    tagline: 'Elevating leadership into authoritative industry voices.',
    shortDescription: 'Strategic communications support through Thought Leadership.',
    fullDescription: 'We partner with enterprise founders, chairpersons, and managing directors to articulate profound, forward-looking viewpoints that build enduring intellectual authority.',
    capabilities: [
      'Executive Op-Ed Drafting & Commentary',
      'Keynote & Panel Speaking Alignment',
      'Whitepapers & Industry Point-of-View Briefs',
      'Executive Discussion & Roundtable Formats',
      'Industry Honors & Profile Positioning',
    ],
    process: [
      { step: '01', title: 'Perspective Synthesis', description: 'Structured interviews to distill original industry viewpoints and insights.' },
      { step: '02', title: 'Editorial Formulation', description: 'Drafting rigorous op-eds, survey insights, and analytical essays.' },
      { step: '03', title: 'Platform Placement', description: 'Securing placement in respected business periodicals and industry stages.' },
      { step: '04', title: 'Content Amplification', description: 'Syndicating executive ideas across professional channels and policy circles.' },
    ],
    relatedIndustries: ['Startups', 'Professional Services', 'Corporate Organizations'],
  },
  {
    slug: 'content-development',
    name: 'Content Development',
    category: 'Editorial Practice',
    tagline: 'High-caliber narrative and corporate storytelling.',
    shortDescription: 'Strategic communications support through Content Development.',
    fullDescription: 'Crafting content that satisfies analytical scrutiny and engages stakeholder attention through clear, compelling corporate and brand storytelling.',
    capabilities: [
      'Corporate Profiles & Brand Overviews',
      'Institutional Reports & Case Briefs',
      'Executive Newsletters & Dispatches',
      'Brand & Video Narrative Scripts',
      'Press Kits & Media Dossiers',
    ],
    process: [
      { step: '01', title: 'Narrative Discovery', description: 'Uncovering authentic operational milestones and enterprise highlights.' },
      { step: '02', title: 'Editorial Drafting', description: 'Drafting clear, compelling copy adhering to high publication standards.' },
      { step: '03', title: 'Design & Visual Integration', description: 'Pairing text with clean corporate presentation and visual design.' },
      { step: '04', title: 'Distribution Alignment', description: 'Deploying long-form documents, digital releases, and executive summaries.' },
    ],
    relatedIndustries: ['Real Estate', 'Retail', 'Education'],
  },
  {
    slug: 'crisis-communications',
    name: 'Crisis Communications',
    category: 'Emergency Advisory',
    tagline: 'Rapid narrative defense and operational reputation containment.',
    shortDescription: 'Strategic communications support through Crisis Communications.',
    badge: 'Critical Advisory',
    fullDescription: 'Providing responsive crisis communications: evaluating facts in real time, formulating clear holding statements, aligning spokespeople, and defending institutional integrity.',
    capabilities: [
      'Rapid Response Command & Consultation',
      'Holding Statement & Key Message Protocols',
      'Media Inquiries Coordination & Response',
      'Internal & Stakeholder Crisis Messaging',
      'Post-Incident Narrative Rehabilitation',
    ],
    process: [
      { step: '01', title: 'Triage & Assessment', description: 'Immediate threat evaluation, factual verification, and message containment.' },
      { step: '02', title: 'Message Preparation', description: 'Drafting verified holding statements and aligning authorized spokespersons.' },
      { step: '03', title: 'Direct Engagement', description: 'Engaging credentialed journalists directly to prevent speculative coverage.' },
      { step: '04', title: 'Recovery Roadmap', description: 'Post-incident narrative recovery and long-term trust rebuilding.' },
    ],
    relatedIndustries: ['Corporate Organizations', 'Healthcare', 'Infrastructure'],
  },
  {
    slug: 'brand-positioning',
    name: 'Brand Positioning',
    category: 'Strategic Practice',
    tagline: 'Defining distinct, defensible market territory for brands and enterprises.',
    shortDescription: 'Strategic communications support through Brand Positioning.',
    fullDescription: 'Helping leadership establish clear, differentiated market presence through strategic messaging, audience alignment, and disciplined communications architecture.',
    capabilities: [
      'Brand Narrative Architecture',
      'Core Value Proposition Framing',
      'Competitive Messaging Differentiation',
      'Tone of Voice & Verbal Identity Guidelines',
      'Corporate Brand Launch Communications',
    ],
    process: [
      { step: '01', title: 'Market Review', description: 'Evaluating sector landscape, audience expectations, and communication gaps.' },
      { step: '02', title: 'Positioning Definition', description: 'Defining the singular, defensible value assertion that sets the brand apart.' },
      { step: '03', title: 'Framework Creation', description: 'Codifying verbal tone, key messages, elevator narratives, and talking points.' },
      { step: '04', title: 'Rollout Execution', description: 'Executing communications plans to introduce and embed the brand positioning.' },
    ],
    relatedIndustries: ['Startups', 'Retail', 'Hospitality'],
  },
  {
    slug: 'digital-communications',
    name: 'Digital Communications',
    category: 'Digital Practice',
    tagline: 'Strategic corporate narrative dissemination across digital channels.',
    shortDescription: 'Strategic communications support through Digital Communications.',
    fullDescription: 'Curating executive professional presence, corporate digital communication, and digital brand reputation with strategy and precision.',
    capabilities: [
      'Executive LinkedIn & Professional Profile Strategy',
      'Corporate Social Channel Messaging Guidelines',
      'Digital Narrative Monitoring & Sentiment Awareness',
      'Digital Milestone & Announcement Campaigns',
      'Online Brand Footprint Optimization',
    ],
    process: [
      { step: '01', title: 'Digital Audit', description: 'Reviewing current channel footprint, audience engagement, and visibility.' },
      { step: '02', title: 'Editorial Rhythm', description: 'Developing structured content themes aligned with organizational milestones.' },
      { step: '03', title: 'Content Execution', description: 'Publishing structured briefings, articles, and leadership perspectives.' },
      { step: '04', title: 'Review & Optimization', description: 'Evaluating narrative reach, professional feedback, and brand resonance.' },
    ],
    relatedIndustries: ['Startups', 'Education', 'Public Affairs'],
  },
];
